// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6014wBKvV1ycwLkC4g1nYv8NZiawvaQ',
    appId: '1:796468182262:web:851246b416dbea458b80d7',
    messagingSenderId: '796468182262',
    projectId: 'mini-app-886e8',
    authDomain: 'mini-app-886e8.firebaseapp.com',
    storageBucket: 'mini-app-886e8.firebasestorage.app',
    measurementId: 'G-6QDW505Q7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbBSVqhPACF_NI54ScMt_lgrXvx5mixw',
    appId: '1:796468182262:android:e04be640205e99028b80d7',
    messagingSenderId: '796468182262',
    projectId: 'mini-app-886e8',
    storageBucket: 'mini-app-886e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FIyCUF2NnJiBLaL1Gz5Tp6vQOA3_0Ps',
    appId: '1:796468182262:ios:669a7149881f97808b80d7',
    messagingSenderId: '796468182262',
    projectId: 'mini-app-886e8',
    storageBucket: 'mini-app-886e8.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FIyCUF2NnJiBLaL1Gz5Tp6vQOA3_0Ps',
    appId: '1:796468182262:ios:669a7149881f97808b80d7',
    messagingSenderId: '796468182262',
    projectId: 'mini-app-886e8',
    storageBucket: 'mini-app-886e8.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk6014wBKvV1ycwLkC4g1nYv8NZiawvaQ',
    appId: '1:796468182262:web:684d9322a632e0668b80d7',
    messagingSenderId: '796468182262',
    projectId: 'mini-app-886e8',
    authDomain: 'mini-app-886e8.firebaseapp.com',
    storageBucket: 'mini-app-886e8.firebasestorage.app',
    measurementId: 'G-9DFDD2M9WH',
  );
}
